#!/usr/bin/env fish

if test (count $argv) -eq 1
	set opt_param $argv
else
	set opt_param ''
end

cd ~/.dotfiles

set DOTDIR $HOME/.dotfiles

### dirs
set dotdirs \
	.byobu \
	.certs \
	.cheatsheets \
	.gitosis-admin \
	.git-templates \
	.nvm \
	.pip \
	.terminfo \
	.tmuxinator \
	.vim \

### files
set dotfiles \
	.alacritty.yml \
	.bashrc \
	.cfnlintrc \
	.direnvrc \
	.dockercfg \
	.editorconfig \
	.gemrc \
	.gitconfig \
	.gitattributes \
	.gitexcludes \
	.gitignore \
	.gitignore_global \
	.gitk \
	.hyper.js \
	.inputrc \
	.nvimrc \
	.pylintrc \
	.pyhistory \
	.pythonrc.py \
	.python-gitlab.cfg \
	.rclone.conf \
	.screenrc \
	.serverlessrc \
	.sublimelinterrc \
	.taskrc \
	.tmux.conf \
	.ungitrc \
	.wgetrc \

set harddirs \
	.config \
	.local \

set tmpdirs ~/.Trash

function doIt
	echo "running doIt() ..."

	set platform unknown
	set unamestr (uname)
	if test $unamestr = 'Linux'
		set platform linux
	else if test $unamestr = 'Darwin'
		set platform freebsd
	end

	mkdir -p ~/.venvs
	ln -s -f $DOTDIR/.venvs/global_requirements.txt ~/.venvs/

	for dir in $dotdirs
		echo "creating directory symlink: $dir..."
		ln -s -f $DOTDIR/$dir ~
	end

	for dir in $harddirs
		echo "rsyncing directory: $dir..."
		rsync -av $DOTDIR/$dir/ ~/$dir/
	end

	for file in $dotfiles
		echo "creating file symlink: $file..."
		ln -s -f $DOTDIR/$file ~
	end

	if test $platform = 'linux'
		echo "platform = linux"
		ln -s -f $DOTDIR/.aliases_linux ~/.aliases
		ln -s -f $DOTDIR/.linuxbrew ~
	else
		echo "platform NOT linux"
	end

	if test $platform = 'freebsd'
		ln -s -f $DOTDIR/.aliases_osx ~/.aliases
		ln -s -f $HOME/Dropbox/etc ~
	end

	for dir in $tmpdirs
		if not test -d $dir
			echo "creating directory $dir..."
			mkdir $dir
		end
	end

	echo "Done!"

end

function unDoIt
	echo "running unDoIt() ..."
	rm -f $HOME/.venvs/global_requirements.txt

	for dir in $dotdirs
		echo "removing directory symlink: $dir..."
		rm  -rf "$HOME/$dir"
	end

	for file in $dotfiles
		echo "removing file symlink: $file..."
		rm  -f "$HOME/$file"
	end

	for file in $zdotfiles
		echo "removing file symlink: $file..."
		rm  -f "$HOME/$file"
	end

	echo "Undone!"

end

if test $opt_param = 'remove'
	unDoIt
else
	doIt
end

set -e doIt
set -e unDoIt
