#!/usr/bin/env fish

if test (count $argv) -eq 1
	set opt_param $argv
else
	set opt_param ''
end

set platform unknown
set unamestr (uname)
if test $unamestr = 'Linux'
	set platform linux
else if test $unamestr = 'Darwin'
	set platform freebsd
end

cd ~/.dotfiles

set DOTDIR $HOME/.dotfiles

### dirs
set dotdirs \
	.byobu \
	.certs \
	.cheatsheets \
	.gitosis-admin \
	.git-templates \
	.nvm \
	.pip \
	.terminfo \
	.tmuxinator \
	.vim \

### files
set dotfiles \
	.alacritty.yml \
	.bashrc \
	.cfnlintrc \
	.direnvrc \
	.dockercfg \
	.editorconfig \
	.gemrc \
	.gitconfig \
	.gitattributes \
	.gitexcludes \
	.gitignore \
	.gitignore_global \
	.gitk \
	.hyper.js \
	.inputrc \
	.nvimrc \
	.pylintrc \
	.pyhistory \
	.pythonrc.py \
	.python-gitlab.cfg \
	.rclone.conf \
	.screenrc \
	.serverlessrc \
	.sublimelinterrc \
	.taskrc \
	.tmux.conf \
	.ungitrc \
	.wgetrc \

set harddirs \
	.config \
	.local

set omf_plugins \
	age \
	argu \
	aws \
	config \
	direnv \
	expand \
	extract \
	jump \
	pj \
	pyenv \
	python \
	spark \
	weather \


#	z

set tmpdirs ~/.Trash

function doIt
	echo "running doIt() ..."

	mkdir -p ~/.venvs
	ln -s -f $DOTDIR/.venvs/global_requirements.txt ~/.venvs/

	for dir in $dotdirs
		echo "creating directory symlink: $dir..."
		ln -s -f $DOTDIR/$dir ~
	end

	for dir in $harddirs
		echo "rsyncing directory: $dir..."
		rsync -av $DOTDIR/$dir/ ~/$dir/
	end

	for file in $dotfiles
		echo "creating file symlink: $file..."
		ln -s -f $DOTDIR/$file ~
	end

	if test $platform = 'linux'
		echo "platform = linux"
		ln -s -f $DOTDIR/.aliases_linux ~/.aliases
	else if test $platform = 'freebsd'
		echo "platform = freebsd"
		ln -s -f $DOTDIR/.aliases_osx ~/.aliases
		ln -s -f $HOME/Dropbox/etc ~
	else
		echo "platform NOT linux OR freebsd"
	end

	for dir in $tmpdirs
		if not test -d $dir
			echo "creating directory $dir..."
			mkdir $dir
		end
	end

	echo "Installing omf..."
	curl -sL https://get.oh-my.fish > install_omf
	chmod +x install_omf
	#./install_omf --noninteractive
	fish install_omf --noninteractive

	source $HOME/.local/share/omf/init.fish
	echo "Installing bira theme..."
	omf install bira
	omf theme bira

	echo "Installing omf plugins:"
	for plugin in $omf_plugins
		echo "Installing $plugin..."
		omf install $plugin
	end
	exit

	echo "Installing fisher..."
	curl -sL https://git.io/fisher | source && fisher update

	cd
	echo "Done!"

end

function unDoIt
	echo "running unDoIt() ..."
	rm -f $HOME/.venvs/global_requirements.txt

	for dir in $dotdirs
		echo "removing directory symlink: $dir..."
		rm  -rf "$HOME/$dir"
	end

	for file in $dotfiles
		echo "removing file symlink: $file..."
		rm  -f "$HOME/$file"
	end

	for file in $zdotfiles
		echo "removing file symlink: $file..."
		rm  -f "$HOME/$file"
	end

	echo "Undone!"

end

if test $opt_param = 'remove'
	unDoIt
else
	doIt
end

set -e doIt
set -e unDoIt

find $DOTDIR/ -name fish_variables -delete
find $HOME/.config/ -name fish_variables -delete
