# apfs_systemsnapshot
# Autogenerated from man page /usr/share/man/man8/apfs_systemsnapshot.8
complete -c apfs_systemsnapshot -s r --description 'Tag snapshot_name as the root snapshot to boot from upon next boot.'
complete -c apfs_systemsnapshot -s s --description 'Create a new system snapshot named snapshot_name.'
complete -c apfs_systemsnapshot -s h --description 'Print a usage message.'

