# app-sso
# Autogenerated from man page /usr/share/man/man1/app-sso.1
complete -c app-sso -s a --description 'Display the login dialog for the specified realm, or if the user has already …'
complete -c app-sso -s u --description 'The username for authentication.'
complete -c app-sso -s f --description 'Display the login screen even if the user is already authenticated.'
complete -c app-sso -s q --description 'Suppress the information that is normally printed after authentication.  El.'
complete -c app-sso -s d --description 'Logs out any user logged into the specified realm.'
complete -c app-sso -s c --description 'Displays the "Change Password" dialog for the specified realm.'
complete -c app-sso -s l --description 'Prints the list of configured realms.'
complete -c app-sso -s i --description 'Print information about the currently configured realm.'
complete -c app-sso -s v --description 'Print the complete site code cache in the results.  El.'
complete -c app-sso -s s --description 'Perform a site lookup for the specified realm.  -tag -width -indent.'
complete -c app-sso -s r --description 'Reset the cache for the specified realm.'
complete -c app-sso -s k --description 'Resets the "login automatically" option for the specified realm.'
complete -c app-sso -s p --description 'Allow user setup to proceed if you are using "delayUserSetup" in your configu…'
complete -c app-sso -s t --description 'Prints the kerberos settings that are shared with other processes for the spe…'
complete -c app-sso -s j --description 'Format the output of this command as JSON instead of property list format.'
complete -c app-sso -s h --description 'Print a synopsis of the above document.'

