# avmediainfo
# Autogenerated from man page /usr/share/man/man1/avmediainfo.1
complete -c avmediainfo -o '\\-formatextensions' --description 'Displays format description extensions for each track.'
complete -c avmediainfo -o '\\-samples' --description 'Lists high level sample information for each track (Decode Time(stamp), Prese…'
complete -c avmediainfo -o '\\-chunks' --description 'Lists high level chunk information (Index, Offset, Size, Sample Count, Sample…'
complete -c avmediainfo -o '\\-interleave' --description 'Shows the interleave by listing the chunks in offset order.'
complete -c avmediainfo -o '\\-integeroffsets' --description 'Displays all offsets as integers, instead of hex.'
complete -c avmediainfo -o '\\-brief' --description 'Displays a brief description of the movie.'
complete -c avmediainfo -o '\\-help' --description 'Show help.  Ed.'
complete -c avmediainfo -o '\\-metadata' --description 'Displays metadata information based on options provided.'
complete -c avmediainfo -o '\\-mediatype' --description 'Restricts which tracks have chunk and/or sample information displayed based o…'

