# bmtool
# Autogenerated from man page /usr/share/man/man1/bmtool.1
complete -c bmtool -s a --description 'Description of -a flag.'
complete -c bmtool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

