# bputil
# Autogenerated from man page /usr/share/man/man1/bputil.1
complete -c bputil -s u --description 'Pp Used to specify the username for a user with access to the signing key to …'
complete -c bputil -s p --description 'Pp Used to specify the password for a user with access to the signing key to …'
complete -c bputil -s v --description 'Pp Specify the APFS Volume Group UUID of the OS intended to have its policy c…'
complete -c bputil -s l --description 'Pp Enables verbose logging to assist in debugging any issues associated with …'
complete -c bputil -s d --description 'Pp Display the detailed contents of the LocalPolicy.'
complete -c bputil -s f --description 'Pp Changes security mode to Full Security.'
complete -c bputil -s g --description 'Pp Selecting this option will make your system easier to compromise! Pp This …'
complete -c bputil -s n --description 'Pp Selecting this option will make your system easier to compromise! Pp This …'
complete -c bputil -s k --description 'Pp Because this option automatically downgrades to Reduced Security mode if n…'
complete -c bputil -s c --description 'Pp Because this option automatically downgrades to Reduced Security mode if n…'
complete -c bputil -s a --description 'Pp Because this option automatically downgrades to Reduced Security mode if n…'
complete -c bputil -s s --description 'Pp Because this option automatically downgrades to Permissive Security mode i…'
complete -c bputil -s m --description 'Pp Because this option automatically downgrades to Reduced Security mode if n…'

