# compression_tool
# Autogenerated from man page /usr/share/man/man1/compression_tool.1
complete -c compression_tool -o encode --description 'Encode (compress) the input.'
complete -c compression_tool -o decode --description 'Decode (uncompress) the input.'
complete -c compression_tool -o aalgorithm --description 'Set the compression algorithm, valid options are zlib, lzma, lzfse, lz4, lz4_…'
complete -c compression_tool -o Aalgorithm --description 'Enable block compression, and set compression algorithm, valid options are zl…'
complete -c compression_tool -o bblock_size --description 'Set block size for block compression.'
complete -c compression_tool -o tthread_count --description 'Set the number of worker threads to use for block compression/decompression.'
complete -c compression_tool -o iinput_file --description 'Input file.  If omitted, read from standard input.'
complete -c compression_tool -o ooutput_file --description 'Output file.  If omitted, write to standard output.'
complete -c compression_tool -s v --description 'Increase verbosity.  Default is silent operation.'
complete -c compression_tool -s a --description 'Set the compression algorithm, valid options are zlib, lzma, lzfse, lz4, lz4_…'
complete -c compression_tool -s A --description 'Enable block compression, and set compression algorithm, valid options are zl…'
complete -c compression_tool -s b --description 'Set block size for block compression.'
complete -c compression_tool -s t --description 'Set the number of worker threads to use for block compression/decompression.'
complete -c compression_tool -s i --description 'Input file.  If omitted, read from standard input.'
complete -c compression_tool -s o --description 'Output file.  If omitted, write to standard output.'
complete -c compression_tool -s h --description 'Print usage and exit.'

