# containermanagerd
# Autogenerated from man page /usr/share/man/man8/containermanagerd.8
complete -c containermanagerd -l runmode --description 'Defines the running mode of the daemon where runmode is one of the following:…'
complete -c containermanagerd -l default-user --description 'Sets the default user where user data will be stored.'
complete -c containermanagerd -l bundle-container-mode --description 'Controls how bundle containers are managed where mode is one of the following…'
complete -c containermanagerd -l bundle-container-owner --description 'Sets the username that bundle containers will be chown 2 to.'
complete -c containermanagerd -l system-container-mode --description 'Controls how system containers are managed where mode is one of the following…'
complete -c containermanagerd -l system-container-owner --description 'Sets the username that system containers will be chown 2 to.'

