# dedutil
# Autogenerated from man page /usr/share/man/man1/dedutil.1
complete -c dedutil -s a --description 'Description of -a flag.'
complete -c dedutil -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

