# diagnosticextensionsd
# Autogenerated from man page /usr/share/man/man1/diagnosticextensionsd.1
complete -c diagnosticextensionsd -s a --description 'Description of -a flag.'
complete -c diagnosticextensionsd -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

