# FileCheck-3
# Autogenerated from man page /usr/share/man/man1/FileCheck-3.8.1.gz
complete -c FileCheck-3 -o help --description 'Print a summary of command line options.'
complete -c FileCheck-3 -l check-prefix --description 'FileCheck searches the contents of match-filename for patterns to match.'
complete -c FileCheck-3 -l input-file --description 'File to check (defaults to stdin).'
complete -c FileCheck-3 -l strict-whitespace --description 'By default, FileCheck canonicalizes input horizontal whitespace (spaces and t…'
complete -c FileCheck-3 -l implicit-check-not --description 'Adds implicit negative checks for the specified patterns between positive che…'
complete -c FileCheck-3 -o version --description 'Show the version number of this program.'
complete -c FileCheck-3 -o verify --description 'warnings not covered by any CHECK: patterns.'

