# gunicorn-debian
# Autogenerated from man page /usr/share/man/man8/gunicorn-debian.8.gz
complete -c gunicorn-debian -s h -l help --description 'show this help message and exit . HP --conf-dir=\\,CONF_DIR\\/ .'
complete -c gunicorn-debian -l conf-dir --description '.'
complete -c gunicorn-debian -l pid-dir --description '.'
complete -c gunicorn-debian -l log-dir --description '.'
complete -c gunicorn-debian -s v -l verbosity --description 'Verbosity level; 0=minimal output, 1=normal output 2=verbose output, 3=very v…'

