# gunicorn_paster
# Autogenerated from man page /usr/share/man/man1/gunicorn_paster.1.gz
complete -c gunicorn_paster -s c -l config --description 'Config file.  [none].'
complete -c gunicorn_paster -s b -l bind --description 'Address to listen on.  Ex.  127. 0. 0. 1:8000 or unix:/tmp/gunicorn. sock.'
complete -c gunicorn_paster -s w -l workers --description 'Number of workers to spawn.  [1].'
complete -c gunicorn_paster -s a -l arbiter --description 'gunicorn arbiter entry point or module [egg:gunicorn#main].'
complete -c gunicorn_paster -s p -l pid --description 'Set the background \\s-1PID FILE\\s0.'
complete -c gunicorn_paster -s D -l daemon --description 'Run daemonized in the background.'
complete -c gunicorn_paster -s m -l umask --description 'Define umask of daemon process.'
complete -c gunicorn_paster -s u -l user --description 'Change worker user.'
complete -c gunicorn_paster -s g -l group --description 'Change worker group.'
complete -c gunicorn_paster -s n -l name --description 'Process name.'
complete -c gunicorn_paster -l log-level --description 'Log level below which to silence messages.  [info].'
complete -c gunicorn_paster -l log-file --description 'Log to a file.  - equals stdout.  [-].'
complete -c gunicorn_paster -l debug --description 'Debug mode.  only 1 worker.'
complete -c gunicorn_paster -l version --description 'Show program\'s version number and exit.'

