# java_home
# Autogenerated from man page /usr/share/man/man1/java_home.1
complete -c java_home -s v -l version --description 'Filters the returned JVMs by version (as if JAVA_VERSION had been set in the …'
complete -c java_home -s a -l arch --description 'Filters the returned JVMs by the architecture they support (as if JAVA_ARCH h…'
complete -c java_home -s F -l failfast --description 'Immediately fails when filters return no JVMs; does not print out the path to…'
complete -c java_home -l exec --description 'Executes the command at $JAVA_HOME/bin/<command> and passes the remaining arg…'
complete -c java_home -s X -l xml --description 'Prints a list of all matching JVMs and associated properties as an XML plist …'
complete -c java_home -s V -l verbose --description 'Prints a list of all matching JVMs and architectures to stderr.'
complete -c java_home -s h -l help --description 'Brief usage information.'

