# llvm-nm-3
# Autogenerated from man page /usr/share/man/man1/llvm-nm-3.8.1.gz
complete -c llvm-nm-3 -s B --description 'Use BSD output format.   Alias for --format=bsd.'
complete -c llvm-nm-3 -s P --description 'Use POSIX. 2 output format.   Alias for --format=posix.'
complete -c llvm-nm-3 -l debug-syms -s a --description 'Show all symbols, even debugger only.'
complete -c llvm-nm-3 -l defined-only --description 'Print only symbols defined in this file (as opposed to symbols which may be r…'
complete -c llvm-nm-3 -l dynamic -s D --description 'Display dynamic symbols instead of normal symbols.'
complete -c llvm-nm-3 -l extern-only -s g --description 'Print only symbols whose definitions are external; that is, accessible from o…'
complete -c llvm-nm-3 -l format -s f --description 'Select an output format; format may be sysv, posix, or bsd.'
complete -c llvm-nm-3 -o help --description 'Print a summary of command-line options and their meanings.'
complete -c llvm-nm-3 -l no-sort -s p --description 'Shows symbols in order encountered.'
complete -c llvm-nm-3 -l numeric-sort -s n -s v --description 'Sort symbols by address.'
complete -c llvm-nm-3 -l print-file-name -s A -s o --description 'Precede each symbol with the file it came from.'
complete -c llvm-nm-3 -l print-size -s S --description 'Show symbol size instead of address.'
complete -c llvm-nm-3 -l size-sort --description 'Sort symbols by size.'
complete -c llvm-nm-3 -l undefined-only -s u --description 'Print only symbols referenced but not defined in this file.'

