# llvm-profdata-3
# Autogenerated from man page /usr/share/man/man1/llvm-profdata-3.8.1.gz
complete -c llvm-profdata-3 -o help --description 'Print a summary of command line options.'
complete -c llvm-profdata-3 -o output -s o --description 'Specify the output file name.'
complete -c llvm-profdata-3 -o weighted-input --description 'Specify an input file name along with a weight.'
complete -c llvm-profdata-3 -o instr --description 'Specify that the input profile is an instrumentation-based profile.'
complete -c llvm-profdata-3 -o sample --description 'Specify that the input profile is a sample-based profile.'
complete -c llvm-profdata-3 -o binary --description 'Emit the profile using a binary encoding.'
complete -c llvm-profdata-3 -o text --description 'Emit the profile in text mode.'
complete -c llvm-profdata-3 -o gcc --description 'Emit the profile using GCC\'s gcov format (Not yet supported).'
complete -c llvm-profdata-3 -o all-functions --description 'Print details for every function.'
complete -c llvm-profdata-3 -o counts --description 'Print the counter values for the displayed functions.'
complete -c llvm-profdata-3 -o function --description 'Print details for a function if the function\'s name contains the given string.'

