# llvm-dis-3
# Autogenerated from man page /usr/share/man/man1/llvm-dis-3.8.1.gz
complete -c llvm-dis-3 -s o --description 'OPTIONS.'
complete -c llvm-dis-3 -s f --description 'Enable binary output on terminals.'
complete -c llvm-dis-3 -o help --description 'Print a summary of command line options.'

