# llvm-symbolizer-3
# Autogenerated from man page /usr/share/man/man1/llvm-symbolizer-3.8.1.gz
complete -c llvm-symbolizer-3 -o obj --description 'Path to object file to be symbolized.'
complete -c llvm-symbolizer-3 -o functions --description 'Specify the way function names are printed (omit function name, print short f…'
complete -c llvm-symbolizer-3 -o use-symbol-table --description 'Prefer function names stored in symbol table to function names in debug info …'
complete -c llvm-symbolizer-3 -o demangle --description 'Print demangled function names.  Defaults to true.'
complete -c llvm-symbolizer-3 -o inlining --description 'If a source code location is in an inlined function, prints all the inlnied f…'
complete -c llvm-symbolizer-3 -o default-arch --description 'If a binary contains object files for multiple architectures (e. g.'
complete -c llvm-symbolizer-3 -o dsym-hint --description '(Darwin-only flag).'
complete -c llvm-symbolizer-3 -o print-address --description 'Print address before the source code location.  Defaults to false.'
complete -c llvm-symbolizer-3 -o pretty-print --description 'Print human readable output.'

