# llvm-stress-3
# Autogenerated from man page /usr/share/man/man1/llvm-stress-3.8.1.gz
complete -c llvm-stress-3 -s o --description 'Specify the output filename.'
complete -c llvm-stress-3 -o size --description 'Specify the size of the generated . ll file.'
complete -c llvm-stress-3 -o seed --description 'Specify the seed to be used for the randomly generated instructions.'

