# llvm-extract-3
# Autogenerated from man page /usr/share/man/man1/llvm-extract-3.8.1.gz
complete -c llvm-extract-3 -s f --description 'Enable binary output on terminals.'
complete -c llvm-extract-3 -l func --description 'Extract the function named function-name from the LLVM bitcode.'
complete -c llvm-extract-3 -l rfunc --description 'Extract the function(s) matching function-regular-expr from the LLVM bitcode.'
complete -c llvm-extract-3 -l glob --description 'Extract the global variable named global-name from the LLVM bitcode.'
complete -c llvm-extract-3 -l rglob --description 'Extract the global variable(s) matching global-regular-expr from the LLVM bit…'
complete -c llvm-extract-3 -o help --description 'Print a summary of command line options.'
complete -c llvm-extract-3 -s o --description 'Specify the output filename.'
complete -c llvm-extract-3 -s S --description 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS.'

