# llvm-config-3
# Autogenerated from man page /usr/share/man/man1/llvm-config-3.8.1.gz
complete -c llvm-config-3 -l version --description 'Print the version number of LLVM.'
complete -c llvm-config-3 -o help --description 'Print a summary of llvm-config arguments.'
complete -c llvm-config-3 -l prefix --description 'Print the installation prefix for LLVM.'
complete -c llvm-config-3 -l src-root --description 'Print the source root from which LLVM was built.'
complete -c llvm-config-3 -l obj-root --description 'Print the object root used to build LLVM.'
complete -c llvm-config-3 -l bindir --description 'Print the installation directory for LLVM binaries.'
complete -c llvm-config-3 -l includedir --description 'Print the installation directory for LLVM headers.'
complete -c llvm-config-3 -l libdir --description 'Print the installation directory for LLVM libraries.'
complete -c llvm-config-3 -l cxxflags --description 'Print the C++ compiler flags needed to use LLVM headers.'
complete -c llvm-config-3 -l ldflags --description 'Print the flags needed to link against LLVM libraries.'
complete -c llvm-config-3 -l libs --description 'Print all the libraries needed to link against the specified LLVM components,…'
complete -c llvm-config-3 -l libnames --description 'Similar to --libs, but prints the bare filenames of the libraries without -l …'
complete -c llvm-config-3 -l libfiles --description 'Similar to --libs, but print the full path to each library file.'
complete -c llvm-config-3 -l components --description 'Print all valid component names.'
complete -c llvm-config-3 -l targets-built --description 'Print the component names for all targets supported by this copy of LLVM.'
complete -c llvm-config-3 -l build-mode --description 'Print the build mode used when LLVM was built (e. g.'

