# ln
# Autogenerated from man page /usr/share/man/man1/ln.1
complete -c ln -s F --description 'If the proposed link (link_name) already exists and is a directory, then remo…'
complete -c ln -s h --description 'If the link_name or link_dirname is a symbolic link, do not follow it.'
complete -c ln -s f --description 'If the proposed link (link_name) already exists, then unlink it so that the l…'
complete -c ln -s i --description 'Cause ln ln to write a prompt to standard error if the proposed link exists.'
complete -c ln -s n --description 'Same as h, for compatibility with other ln ln implementations.'
complete -c ln -s s --description 'Create a symbolic link.'
complete -c ln -s v --description 'Cause ln ln to be verbose, showing files as they are processed.'

