# mandoc_soelim
# Autogenerated from man page /usr/share/man/man1/mandoc_soelim.1
complete -c mandoc_soelim -s C --description 'Recognise . so when not followed by a space character.'
complete -c mandoc_soelim -s r --description 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing).'
complete -c mandoc_soelim -s t --description 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing).'
complete -c mandoc_soelim -s v --description 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing).'
complete -c mandoc_soelim -s I --description 'This option specify directories where mandoc_soelim searches for files (both …'

