# mount_tmpfs
# Autogenerated from man page /usr/share/man/man8/mount_tmpfs.8
complete -c mount_tmpfs -s o --description 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_tmpfs -s i --description 'Make the volume case-insensitive (default).'
complete -c mount_tmpfs -s e --description 'Make the volume case-sensitive.'
complete -c mount_tmpfs -s n --description 'Set the maximum number of nodes available to the file system to max_nodes.'
complete -c mount_tmpfs -s s --description 'Set the maximum total file system size to max_mem_size bytes, unless suffixed…'

