# psm
# Autogenerated from man page /usr/share/man/man1/psm.1
complete -c psm -s d --description 'specify a disk to operate on <disk3s5>.'
complete -c psm -s s --description 'specify a specifc slot number.'
complete -c psm -s v --description 'will make psm more verbose.'

