# sntp
# Autogenerated from man page /usr/share/man/man1/sntp.1
complete -c sntp -s d --description 'Enable debug logging.'
complete -c sntp -s g --description 'Gap betwen requests in milliseconds.'
complete -c sntp -s r --description 'bind(2) the NTP reserved port (123) for source communications.'
complete -c sntp -s S --description 'Use settimeofday(2) to set the system clock if the offset is greater than 50 …'
complete -c sntp -s s --description 'Use adjtime(2) to slew the system clock if the offset is less than 50 millise…'
complete -c sntp -s t --description 'Maximum number of seconds to wait for responses.'

