# softwareupdate
# Autogenerated from man page /usr/share/man/man8/softwareupdate.8
complete -c softwareupdate -s l --description 'List all available updates.'
complete -c softwareupdate -s i --description 'Each update specified by args is downloaded and installed.'
complete -c softwareupdate -s d --description 'Each update specified by args is downloaded but not installed.'
complete -c softwareupdate -l schedule --description 'Returns the per-machine automatic (background) check preference.'
complete -c softwareupdate -s h --description 'Print command usage.'

