# visudo
# Autogenerated from man page /usr/share/man/man8/visudo.8
complete -c visudo -l with-editor --description 'configure option.'
complete -c visudo -l with-env-editor --description 'configure option.'
complete -c visudo -s c -l check --description 'Enable check-only mode.'
complete -c visudo -s q --description 'option was specified.'
complete -c visudo -s f -l file --description 'Specify an alternate sudoers file location, see below.  As of version 1. 8.'
complete -c visudo -s h -l help --description 'Display a short help message to the standard output and exit.'
complete -c visudo -l quiet --description 'Enable quiet mode.  In this mode details about syntax errors are not printed.'
complete -c visudo -s s -l strict --description 'Enable strict checking of the sudoers file.'
complete -c visudo -s V -l version --description 'Print the visudo and sudoers grammar versions and exit.'

